name: Publish Docker Image
on:
  workflow_dispatch:
    branches:
    - master
  push:
    branches:
    - master
    - v1.7
    - v2.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and Publish to Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jonatanmc/openotp
        tag_with_ref: true
